name: Manage pull request labels

on:
  pull_request_target:
    types:
      - unlabeled

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.label.name }}
  cancel-in-progress: true

env:
  GH_REPO: ${{ github.repository }}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1
  HOMEBREW_DISABLE_LOAD_FORMULA: 1
  PR: ${{ github.event.number }}

jobs:
  label:
    permissions:
      pull-requests: write # for `gh pr edit`
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'Homebrew' &&
      contains(fromJson('["workflows"]'), github.event.label.name)
    steps:
      - name: Re-label PR
        run: gh pr edit "$PR" --add-label "$LABEL" --repo "$GITHUB_REPOSITORY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: ${{ github.event.label.name }}
